spring:
  application:
    name: eureka-consumer-feign
server:
  port: 8003
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://dmxs:123456@localhost:8000/eureka