spring:
  application:
    name: eureka-consumer-resttemplate
server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://dmxs:123456@localhost:8000/eureka

