spring:
  application:
    name: eureka-client-dmxs
server:
  port: 9012
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://dmxs:123456@localhost:8000/eureka
