spring:
  application:
    name: eureka-consumer-feign-hystrix
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8103
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://dmxs:123456@localhost:8000/eureka