spring:
  application:
    name: eureka-consumer-ribbon
server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://dmxs:123456@localhost:8000/eureka